apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 1188
      targetPort: 3188
      nodePort: 30000
