apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classroom
  template:
    metadata:
      labels:
        app: classroom
    spec:
      containers:
        - name: classroom
          image: sheraztariq22/classroom_img
          ports:
            - containerPort: 3189
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
