apiVersion: v1
kind: Service
metadata:
  name: classroom-service
spec:
  type: NodePort
  selector:
    app: classroom
  ports:
    - protocol: TCP
      port: 1188
      targetPort: 3189
      nodePort: 30001
