apiVersion: v1
kind: Service
metadata:
  name: eventbus-service
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 1188
      targetPort: 3191
      nodePort: 30003
